# Generated by Django 5.1.6 on 2025-03-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
